#Requires -Version 5.1
Describe 'DscConfiguration' {
    BeforeAll {
        $root = Split-Path $PSScriptRoot -Parent
        Import-Module (Join-Path $root 'helpers\DscConfiguration.psm1') -Force
    }

    It 'marks current packages Present and removed packages Absent' {
        $current = @(
            @{ Id = 'Git.Git'; Category = 'Dev'; Comment = 'git'; AllowPrerelease = $false }
            @{ Id = 'GoLang.Go'; Category = 'Dev'; Comment = ''; AllowPrerelease = $false }
        )
        $previous = @(
            @{ Id = 'Git.Git'; Category = 'Dev'; Comment = 'git'; AllowPrerelease = $false }
            @{ Id = 'Old.Package'; Category = 'Dev'; Comment = 'gone'; AllowPrerelease = $false }
        )

        $result = Resolve-PackageLifecycle -CurrentEntries $current -PreviousEntries $previous -ExistingEnsure @{}

        $result.AddedIds | Should -Contain 'GoLang.Go'
        $result.RemovedIds | Should -Contain 'Old.Package'
        $result.PrunedIds.Count | Should -Be 0

        $byId = @{}
        foreach ($e in $result.FinalEntries)
        {
            $byId[$e.Id] = $e
        }

        $byId['Git.Git'].Ensure | Should -Be 'Present'
        $byId['GoLang.Go'].Ensure | Should -Be 'Present'
        $byId['Old.Package'].Ensure | Should -Be 'Absent'
    }

    It 'prunes stale Absent entries not in previous or current YAML' {
        $current = @(
            @{ Id = 'Git.Git'; Category = 'Dev'; Comment = ''; AllowPrerelease = $false }
        )
        $previous = @(
            @{ Id = 'Git.Git'; Category = 'Dev'; Comment = ''; AllowPrerelease = $false }
        )
        $existing = @{
            'Git.Git'      = 'Present'
            'Stale.Package' = 'Absent'
        }

        $result = Resolve-PackageLifecycle -CurrentEntries $current -PreviousEntries $previous -ExistingEnsure $existing

        $result.PrunedIds | Should -Contain 'Stale.Package'
        $ids = @($result.FinalEntries | ForEach-Object { $_.Id })
        $ids | Should -Not -Contain 'Stale.Package'
    }

    It 'builds stable DSC YAML with allowPrerelease default false' {
        $entries = @(
            @{
                Id              = 'Git.Git'
                Category        = 'Development tools'
                Comment         = 'Git version control'
                AllowPrerelease = $false
                Ensure          = 'Present'
            }
            @{
                Id              = 'Nightly.App'
                Category        = 'Development tools'
                Comment         = 'nightly'
                AllowPrerelease = $true
                Ensure          = 'Present'
            }
        )

        $yaml1 = Build-DscYaml -Entries $entries -SourceFile 'winget-packages.yml'
        $yaml2 = Build-DscYaml -Entries $entries -SourceFile 'winget-packages.yml'

        $yaml1 | Should -Be $yaml2
        $yaml1 | Should -Match 'allowPrerelease: false'
        $yaml1 | Should -Match 'allowPrerelease: true'
        $yaml1 | Should -Match 'id: Git.Git'
        $yaml1 | Should -Match 'ensure: Present'
        $yaml1 | Should -Not -Match 'Generated by New-WingetConfiguration\.ps1 on '
    }

    It 'reads ensure map from DSC YAML text via temp file' {
        $dsc = @'
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Git.Git
        ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      settings:
        id: Old.Package
        ensure: Absent
'@
        $temp = Join-Path ([System.IO.Path]::GetTempPath()) ("dsc-test-{0}.yaml" -f [guid]::NewGuid())
        try
        {
            [System.IO.File]::WriteAllText($temp, $dsc)
            $map = Read-DscEnsureMap -Path $temp
            $map['Git.Git'] | Should -Be 'Present'
            $map['Old.Package'] | Should -Be 'Absent'
        }
        finally
        {
            Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue
        }
    }
}
