# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  resources:

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Handbrake
        allowPrerelease: true
      settings:
        id: Handbrake.Handbrake
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Android Studio
        allowPrerelease: true
      settings:
        id: Google.AndroidStudio
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Steam
        allowPrerelease: true
      settings:
        id: Valve.Steam
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: The Gimp
        allowPrerelease: true
      settings:
        id: GIMP.GIMP
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Inkscape
        allowPrerelease: true
      settings:
        id: Inkscape.Inkscape
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Discord
        allowPrerelease: true
      settings:
        id: Discord.Discord
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Quicken
        allowPrerelease: true
      settings:
        id: Quicken.Quicken
        source: winget
     
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Signal
        allowPrerelease: true
      settings:
        id: OpenWhisperSystems.Signal
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: LibreOffice LTS
        allowPrerelease: true
      settings:
        id: TheDocumentFoundation.LibreOffice.LTS
        source: winget
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Proton Drive
        allowPrerelease: true
      settings:
        id: Proton.ProtonDrive
        source: winget
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Proton Mail Bridge
        allowPrerelease: true
      settings:
        id: Proton.ProtonMailBridge
        source: winget
     
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Proton Pass
        allowPrerelease: true
      settings:
        id: Proton.ProtonPass
        source: winget
            
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Proton VPN
        allowPrerelease: true
      settings:
        id: Proton.ProtonVPN
        source: winget      
             
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Mozilla Thunderbird
        allowPrerelease: true
      settings:
        id: Mozilla.Thunderbird
        source: winget
                     
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Mozilla Firefox
        allowPrerelease: true
      settings:
        id: Mozilla.Firefox
        source: winget  

  configurationVersion: 0.2.0