# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  resources:

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Discord
        allowPrerelease: true
      settings:
        id: Discord.Discord
        source: winget
     
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Signal
        allowPrerelease: true
      settings:
        id: OpenWhisperSystems.Signal
        source: winget
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Proton Drive
        allowPrerelease: true
      settings:
        id: Proton.ProtonDrive
        source: winget
     
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Proton Pass
        allowPrerelease: true
      settings:
        id: Proton.ProtonPass
        source: winget
            
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Proton VPN
        allowPrerelease: true
      settings:
        id: Proton.ProtonVPN
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Freda ePub Reader
        allowPrerelease: true
      settings:
        id: 9WZDNCRFJ43B
        source: msstore

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: WorkAtNight - Brightness Below Minimum
        allowPrerelease: true
      settings:
        id: 9PL6P6ZHL1L7
        source: msstore

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: FeedLab RSS Reader
        allowPrerelease: true
      settings:
        id: 9WZDNCRDKRQ3
        source: msstore

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Ungoogle Chromium
        allowPrerelease: true
      settings:
        id: Eloston.UngoogleChromium
        source: winget

  configurationVersion: 0.2.0