# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

properties:
  resources:
    
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Rancher Desktop
        allowPrerelease: true
      settings:
        id: suse.RancherDesktop
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: vim
        allowPrerelease: true
      settings:
        id: vim.vim
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Azure CLI
        allowPrerelease: true
      settings:
        id: Microsoft.AzureCLI
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Python (SNEKS!)
        allowPrerelease: true
      settings:
        id: Python.Python.3.13
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: golang
        allowPrerelease: true
      settings:
        id: GoLang.Go
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Terraform
        allowPrerelease: true
      settings:
        id: HashiCorp.Terraform
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Vault
        allowPrerelease: true
      settings:
        id: HashiCorp.Vault
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Packer
        allowPrerelease: true
      settings:
        id: HashiCorp.Packer
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Consul
        allowPrerelease: true
      settings:
        id: HashiCorp.Consul
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Ruby
        allowPrerelease: true
      settings:
        id: RubyInstallerTeam.RubyWithDevKit.3.2
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: SQLite
        allowPrerelease: true
      settings:
        id: SQLite.SQLite
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: k9s
        allowPrerelease: true
      settings:
        id: Derailed.k9s
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: kubectl
        allowPrerelease: true
      settings:
        id: Kubernetes.kubectl
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: kubectx
        allowPrerelease: true
      settings:
        id: ahmetb.kubectx
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: kubens
        allowPrerelease: true
      settings:
        id: ahmetb.kubens
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Ubuntu 24.04 LTS WSL
        allowPrerelease: true
      settings:
        id: 9NZ3KLHXDJP5
        source: msstore

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Incus Client
        allowPrerelease: true
      settings:
        id: LinuxContainers.Incus
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Virt-Viewer (for Incus VGA console)
        allowPrerelease: true
      settings:
        id: RedHat.VirtViewer
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: VSCode Insiders
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode.Insiders
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Microsoft.Edit editor
        allowPrerelease: true
      settings:
        id: Microsoft.Edit
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Chocolatey
        allowPrerelease: true
      settings:
        id: Chocolatey.Chocolatey
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: AWS CLI
        allowPrerelease: true
      settings:
        id: Amazon.AWSCLI
        source: winget
        
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Microsoft Foundry Local
        allowPrerelease: true
      settings:
        id: Microsoft.FoundryLocal
        source: winget

    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: LM Studio
        allowPrerelease: true
      settings:
        id: ElementLabs.LMStudio
        source: winget
        
  configurationVersion: 0.2.0